+incdir+/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/include
+incdir+/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips
+incdir+/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_i2c

/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/include/config.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/include/e203_defines.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_biu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_clk_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_clkgate.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_core.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_cpu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_cpu_top.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_dtcm_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_dtcm_ram.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_extend_csr.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_alu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_alu_bjp.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_alu_csrctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_alu_dpath.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_alu_lsuagu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_alu_muldiv.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_alu_rglr.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_branchslv.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_commit.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_csr.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_decode.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_disp.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_excp.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_longpwbck.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_nice.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_oitf.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_regfile.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_exu_wbck.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_ifu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_ifu_ifetch.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_ifu_ift2icb.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_ifu_litebpu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_ifu_minidec.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_irq_sync.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_itcm_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_itcm_ram.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_lsu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_lsu_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_reset_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/core/e203_srams.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/debug/sirv_debug_csr.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/debug/sirv_debug_module.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/debug/sirv_debug_ram.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/debug/sirv_debug_rom.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/debug/sirv_jtag_dtm.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/fab/sirv_icb1to16_bus.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/fab/sirv_icb1to2_bus.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/fab/sirv_icb1to8_bus.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_1cyc_sram_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_gnrl_bufs.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_gnrl_dffs.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_gnrl_icbs.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_gnrl_ram.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_gnrl_xchecker.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_sim_ram.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/general/sirv_sram_icb_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/mems/sirv_mrom.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/mems/sirv_mrom_top.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_AsyncResetReg.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_AsyncResetRegVec.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_AsyncResetRegVec_1.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_AsyncResetRegVec_129.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_AsyncResetRegVec_36.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_DeglitchShiftRegister.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_LevelGateway.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_ResetCatchAndSync.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_ResetCatchAndSync_2.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_aon.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_aon_lclkgen_regs.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_aon_porrst.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_aon_top.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_aon_wrapper.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_clint.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_clint_top.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_expl_axi_slv.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_flash_qspi.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_flash_qspi_top.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_hclkgen_regs.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_jtaggpioport.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_plic_man.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_plic_top.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_pmu.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_pmu_core.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_qspi_arbiter.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_qspi_fifo.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_qspi_media.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_qspi_physical.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_queue.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_queue_1.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_repeater_6.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_rtc.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_spi_flashmap.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_tl_repeater_5.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_tlfragmenter_qspi_1.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_tlwidthwidget_qspi.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/sirv_wdog.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/adv_timer_apb_if.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/apb_adv_timer.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/comparator.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/input_stage.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/prescaler.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/timer_cntrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/timer_module.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_adv_timer/up_down_counter.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_gpio/apb_gpio.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_i2c/apb_i2c.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_i2c/i2c_master_bit_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_i2c/i2c_master_byte_ctrl.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_i2c/i2c_master_defines.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_spi_master/apb_spi_master.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_spi_master/spi_master_apb_if.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_spi_master/spi_master_clkgen.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_spi_master/spi_master_controller.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_spi_master/spi_master_fifo.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_spi_master/spi_master_rx.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_spi_master/spi_master_tx.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_uart/apb_uart.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_uart/io_generic_fifo.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_uart/uart_interrupt.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_uart/uart_rx.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/perips/apb_uart/uart_tx.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/soc/e203_soc_top.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_clint.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_gfcm.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_hclkgen.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_hclkgen_rstsync.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_main.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_mems.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_nice_core.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_perips.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_plic.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_pll.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_pllclkdiv.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/subsys/e203_subsys_top.v

/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/user/e203_sirv_icb_slv_test.v
/home/qingteng/Documents/Front_end/BARVINN_project/src/riscv/user/e203_subsys_extperips.v